### ISSUE TITLE
Cant upload file greater than 100kb

### ISSUE THREAD

**Issue by westonganger** [ysbaddaden/prax#109]
I get routing errors when trying to upload a file greater than 100kb.

The problem doesnt exist when running webrick using "rails server"

**Comment by lasseebert** [comment]
I had the same experience. On some files upload fails using prax, but succeeds using unicorn.

I get a Rack error, which looks like this bug: https://github.com/rack/rack/issues/676, but I'm currently stuck at `rack ~> 1.4.5` and have not tested with `1.6.0` yet.

I have not noticed a pattern for which files will fail to upload with prax.

Top of stacktrace:

```
EOFError (bad content body):
  rack (1.4.5) lib/rack/multipart/parser.rb:74:in `block in fast_forward_to_first_boundary'
  rack (1.4.5) lib/rack/multipart/parser.rb:72:in `loop'
  rack (1.4.5) lib/rack/multipart/parser.rb:72:in `fast_forward_to_first_boundary'
  rack (1.4.5) lib/rack/multipart/parser.rb:15:in `parse'
  rack (1.4.5) lib/rack/multipart.rb:25:in `parse_multipart'
  rack (1.4.5) lib/rack/request.rb:336:in `parse_multipart'
  rack (1.4.5) lib/rack/request.rb:201:in `POST'
```

**Comment by MrOutis** [comment]
Look at this:
https://github.com/basecamp/pow/commit/d3f48362713c70bbc1d9452a8b0be9c99214496f
