### ISSUE TITLE
not finding i18n gem but rails s works fine

### ISSUE THREAD

**Issue by murtyk** [ysbaddaden/prax#124]
Without prax, application is working fine with rails s.  Prax is giving gem not found error.

~/.praxconfig is set up with code from the wiki for rvm.

    $ bundle show i18n
    /home/murtykorada/.rvm/gems/ruby-2.2.0/gems/i18n-0.7.0

    $ prax start -f
    RVM project not found at: /home/murtykorada/Documents/apps/market_place_api
    I, [2015-05-21T14:24:32.540884 #8917]  INFO -- : Prax is ready to receive connections on :20559 and :20558.
    I, [2015-05-21T14:24:41.805858 #8917]  INFO -- : Spawning application 'market_place_api' [/home/murtykorada/Documents/apps/market_place_api]
    /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find i18n-0.7.0 in any of the sources (Bundler::GemNotFound)
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/spec_set.rb:85:in `map!'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:132:in `specs'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:177:in `specs_for'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/definition.rb:166:in `requested_specs'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/environment.rb:18:in `requested_specs'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:13:in `setup'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler.rb:122:in `setup'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.7.9/lib/bundler/setup.rb:17:in `<top (required)>'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/murtykorada/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by ysbaddaden** [comment]
I don't know enough of RVM to help more than what the wiki states. Yet, the `RVM project not found at: /home/murtykorada/Documents/apps/market_place_api` puzzles me.

**Comment by pedrovcenteno** [comment]
Hi,

I had the same problem and found the following solution, by Omar Torres, in here:
http://stackoverflow.com/questions/20599920/how-to-solve-could-not-find-i18n-0-6-5-in-any-of-the-sources-bundlergemnotfo

I did:
 bundle pack
 bundle install --path vendor/cache

and prax runs ok now


the console output from prax:

~/projects/blog$ prax start --foreground
I, [2015-06-03T07:44:53.893112 #32186]  INFO -- : Prax is ready to receive connections on :20559 and :20558.
~/projects/blog$ prax start --foreground
I, [2015-06-03T07:51:58.614597 #32301]  INFO -- : Prax is ready to receive connections on :20559 and :20558.
I, [2015-06-03T07:58:09.411997 #32301]  INFO -- : Spawning application 'blog' [/home/pvc/projects/blog]
/home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find i18n-0.7.0 in any of the sources (Bundler::GemNotFound)
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/spec_set.rb:85:in `map!'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/definition.rb:132:in `specs'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/definition.rb:177:in `specs_for'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/definition.rb:166:in `requested_specs'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/environment.rb:18:in `requested_specs'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/runtime.rb:13:in `setup'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler.rb:122:in `setup'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.4/lib/bundler/setup.rb:18:in `<top (required)>'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/pvc/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
I, [2015-06-03T08:07:11.936051 #32301]  INFO -- : Forcing restart of blog (/home/pvc/projects/blog)
I, [2015-06-03T08:07:11.936155 #32301]  INFO -- : Spawning application 'blog' [/home/pvc/projects/blog]

**Comment by pedrovcenteno** [comment]
I forgot to mention I'm using Xubuntu 14.04 and rails 4.2.1
