### ISSUE TITLE
Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound) when prax starts with rails app

### ISSUE THREAD

**Issue by kotubhaskar** [ysbaddaden/prax#129]
Hi,

I am using rails app with RVM and I am using prax.. I could not get my app running even I followed rvm wiki page for prax.

Here is the log.

```
 PRAX_DEBUG=1 prax start --foreground
RVM project not found at: /home/ru2
ruby: warning: RUBY_FREE_MIN is obsolete. Use RUBY_GC_HEAP_FREE_SLOTS instead.
ruby: warning: RUBY_HEAP_MIN_SLOTS is obsolete. Use RUBY_GC_HEAP_INIT_SLOTS instead.
I, [2015-07-07T12:30:49.257646 #5889]  INFO -- : Prax is ready to receive connections on :20559 and :20558.
I, [2015-07-07T12:30:59.864210 #5889]  INFO -- : Spawning application 'market_place_api' [/home/ru2/market_place_api]
D, [2015-07-07T12:30:59.866176 #5889] DEBUG -- : ["/opt/prax/bin/racker", "--server", "/home/ru2/.prax/_sockets/market_place_api.sock"]
/home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.4.2 in any of the sources (Bundler::GemNotFound)
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/spec_set.rb:85:in `map!'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/spec_set.rb:85:in `materialize'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/definition.rb:132:in `specs'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/definition.rb:177:in `specs_for'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/definition.rb:166:in `requested_specs'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/environment.rb:18:in `requested_specs'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/runtime.rb:13:in `setup'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler.rb:122:in `setup'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.7.9/lib/bundler/setup.rb:17:in `<top (required)>'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
E, [2015-07-07T12:31:14.358010 #5889] ERROR -- : ArgumentError: bad argument (expected URI object or URI string)
  /home/ru2/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:1234:in `URI'
  /opt/prax/lib/prax/request.rb:136:in `determine_host'
  /opt/prax/lib/prax/request.rb:75:in `host'
  /opt/prax/lib/prax/handler.rb:66:in `app_name'
  /opt/prax/lib/prax/handler.rb:17:in `handle'
  /opt/prax/lib/prax.rb:21:in `perform'
  /opt/prax/lib/prax/microworker.rb:84:in `block in work'
  /opt/prax/lib/prax/microworker.rb:77:in `each'
  /opt/prax/lib/prax/microworker.rb:77:in `work'
  /opt/prax/lib/prax/microworker.rb:63:in `block in spawn'
I, [2015-07-07T12:31:14.358206 #5889]  INFO -- : Respawning failed worker
D, [2015-07-07T12:31:29.872559 #5889] DEBUG -- : Killing market_place_api (6114)...
```

**Comment by ysbaddaden** [comment]
This duplicates #128

**Comment by ysbaddaden** [comment]
I'm afraid I can't provide much help about RVM. I'm not using it, and I don't use any version manager anymore —I use the [Ruby packages from Brightbox](https://www.brightbox.com/docs/ruby/ubuntu/).

If anybody knows RVM and wants to help, please do!
